version: "3.1"
services:
  api:
    build: .
    container_name: api_users
    restart: always
    depends_on:
      - db 
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes: 
      - .:/usr/app
    links: 
      - db
      
  db: 
    image: mongo:5.0
    container_name: db
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}